version: "3.8"
services:
  server:
    image: plants-psql-api:latest
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PGURI=${PGURI}
      - PORT=${PORT}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT} || exit 1"]
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} || exit 1"]
      interval: 25s
      retries: 5

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
